services:
  s3:
    image: minio/minio
    container_name: intune-cms-s3
    restart: unless-stopped
    environment:
      MINIO_URL: http://localhost:9000
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  db:
    image: postgres:15
    container_name: intune-cms-db
    environment:
      POSTGRES_USER: intune-cms-admin
      POSTGRES_PASSWORD: +K4T1Z4i.0YIqleC
      POSTGRES_DB: intune-cms
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U intune-cms-admin -d intune-cms"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ../backend/intune-cms
      dockerfile: ../backend/intune-cms/Dockerfile
    container_name: intune-cms-backend
    depends_on:
      s3:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/intune-cms
      SPRING_DATASOURCE_USERNAME: intune-cms-admin
      SPRING_DATASOURCE_PASSWORD: +K4T1Z4i.0YIqleC
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      MINIO_URL: http://s3:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin12345
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ../frontend/intune-cms
      dockerfile: ../backend/intune-cms/Dockerfile
    container_name: intune-cms-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - intune-cms-net

networks:
  intune-cms-net:

volumes:
  minio_data:
  postgres_data: